-- ╔════════════════════════════════════════════════════════════════════════════╗
-- ║                                                                            ║
-- ║        🎨 ICONOS PERSONALIZADOS                                            ║
-- ║                                                                            ║
-- ║  Archivo:    icons.lua                                                     ║  
-- ║  NOTA: Este archivo centraliza la definición de iconos usados en la UI.    ║
-- ║        Aquí se agrupan los símbolos para diagnósticos, documentos, git,    ║
-- ║        LSP, completado, UI, depuración, terminal y otros elementos         ║
-- ║        visuales, facilitando su reutilización y cambio.                    ║
-- ║                                                                            ║
-- ║  Organización de iconos:                                                   ║
-- ║    • diagnostics: Iconos para errores, advertencias, información, etc.     ║
-- ║    • documents:   Archivos, carpetas, enlaces y operaciones de archivo     ║
-- ║    • git:         Estados y acciones de Git                                ║
-- ║    • kind:        Tipos de símbolos LSP/completado                         ║
-- ║    • type:        Tipos de datos y estructuras                             ║
-- ║    • ui:          Elementos de la interfaz de usuario                      ║
-- ║                                                                            ║
-- ╚════════════════════════════════════════════════════════════════════════════╝

return {
    diagnostics = {
        Error = ' ',
        Hint = '󰠠 ',
        Information = ' ',
        Question = ' ',
        Warning = ' ',
    },
    documents = {
        File = ' ',
        FileEmpty = ' ',
        Files = ' ',
        Folder = ' ',
        FolderEmpty = ' ',
        OpenFolder = ' ',
        OpenFolderEmpty = ' ',
        SymLink = ' ',
        SymlinkFolder = ' ',
        Import = ' ',
    },
    git = {
        Add = ' ',
        AddAlt = ' ',
        Branch = ' ',
        Diff = ' ',
        DiffAlt = ' ',
        Ignore = '◌ ',
        Mod = ' ',
        Octoface = ' ',
        Remove = ' ',
        RemoveAlt = ' ',
        Rename = ' ',
        Repo = ' ',
        Tag = ' ',
        Untrack = ' ',
        Directory = '',
    },
    kind = {
        Class = ' ',
        Color = ' ',
        Constant = ' ',
        Constructor = '󰈏 ',
        Copilot = ' ',
        Enum = ' ',
        EnumMember = ' ',
        Event = ' ',
        Field = ' ',
        File = ' ',
        Folder = ' ',
        Function = '󰊕 ',
        Interface = ' ',
        Keyword = ' ',
        Method = ' ',
        Module = '',
        Operator = ' ',
        Property = ' ',
        Reference = ' ',
        Snippet = ' ',
        Struct = ' ',
        Text = ' ',
        TypeParameter = ' ',
        Unit = ' ',
        Value = ' ',
        Variable = ' ',
    },
    type = {
        Array = ' ',
        Boolean = '⏻ ',
        Number = ' ',
        Object = ' ',
        String = ' ',
    },
    ui = {
        Arrow = ' ',
        ArrowClosed = ' ',
        ArrowLeft = ' ',
        ArrowOpen = ' ',
        ArrowRight = ' ',
        Bluetooth = ' ',
        Bookmark = ' ',
        Bug = ' ',
        Calendar = ' ',
        Camera = ' ',
        Check = ' ',
        ChevronRight = '',
        Circle = ' ',
        CircleSmall = '● ',
        CircleSmallEmpty = '○ ',
        Clipboard = ' ',
        Close = ' ',
        Code = ' ',
        Collection = ' ',
        Color = ' ',
        Command = ' ',
        Comment = ' ',
        Copilot = ' ',
        CopilotError = ' ',
        Corner = '└ ',
        Dashboard = ' ',
        Database = ' ',
        Download = ' ',
        Edit = ' ',
        Edge = '│ ',
        Electric = ' ',
        Eye = ' ',
        Fire = ' ',
        Firefox = ' ',
        Flag = ' ',
        Game = ' ',
        Gear = ' ',
        GitHub = ' ',
        Heart = ' ',
        History = ' ',
        Home = ' ',
        Incoming = ' ',
        Jump = ' ',
        Keyboard = '  ',
        Ligthbulb = '󰌵 ',
        List = '',
        Lock = ' ',
        Minus = '‒ ',
        Music = '󰝚 ',
        Neovim = ' ',
        NewFile = ' ',
        None = ' ',
        Note = ' ',
        Outgoing = ' ',
        Package = ' ',
        Paint = ' ',
        Pause = ' ',
        Pencil = ' ',
        Person = ' ',
        Pin = ' ',
        Play = ' ',
        Plug = ' ',
        Plus = ' ',
        Power = ' ',
        PowerlineArrowLeft = '',
        PowerlineArrowRight = '',
        PowerlineLeftRound = '',
        PowerlineRightRound = '',
        Project = ' ',
        Question = ' ',
        Reload = ' ',
        Rocket = ' ',
        Save = '󰆓 ',
        Search = ' ',
        Separator = '▊ ',
        SeparatorLight = '▍',
        SeparatorDashed = '┆',
        SignIn = ' ',
        SignOut = ' ',
        Sleep = '󰒲 ',
        Star = ' ',
        Table = ' ',
        Telescope = ' ',
        Terminal = ' ',
        Test = ' ',
        Time = ' ',
        Topline = '‾',
        Trash = ' ',
        User = ' ',
        Vim = ' ',
        Wifi = ' ',
        Windows = ' ',
    },
}
